try {
  console.log("jalan cuy!");
  arrBloc;
  console.log("akhir try");
} catch (err) {
  console.log(`yang error ${err}`);
  console.log(err.stack);
} finally {
  console.log("akan tetap di eksekusi keep legowo...");
}
